config-version: 8

host: "0.0.0.0"
port: 8317

# Management API
allow-remote: true

# Leave this empty.
# Render's MANAGEMENT_PASSWORD will be used instead.
secret-key: ""

disable-control-panel: false
disable-auto-update-panel: false

# Client API keys
api-keys:
  - "__API_KEY__"

# Persistent authentication directory
auth-dir: "/data/auth"

# Logging
logging-to-file: false

debug: false
