services:
  - type: web
    name: cliproxy-api
    runtime: docker

    region: singapore
    plan: starter

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /v1/models

    envVars:

      # THIS IS THE MANAGEMENT LOGIN PASSWORD
      - key: MANAGEMENT_PASSWORD
        generateValue: true

      # API key for /v1/*
      - key: API_KEY
        generateValue: true

      - key: PORT
        value: "8317"

      - key: TZ
        value: "Asia/Dhaka"

    disk:
      name: cliproxy-data
      mountPath: /data
      sizeGB: 1
